name: flutterpoc
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  validate: ^1.7.0
  #flutter_bloc: ^0.9.1
  meta: ">=1.1.6 <2.0.0"
  equatable: ^0.2.0

  # webview_flutter
  webview_flutter: ^0.3.5+3
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^0.7.0
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.0.2
  # https://github.com/a14n/dart-decimal
  decimal: ">=0.1.0 <1.0.0"
  # https://github.com/tekartik/synchronized.dart
  #synchronized: '>=0.1.0 <3.0.0'
  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: '>=0.1.1 <1.0.0'
  # https://github.com/flutterchina/dio
  dio: ^2.1.2
  # https://github.com/mogol/flutter_secure_storage
  flutter_secure_storage: ^3.2.1+1
  # https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.0.4
  flutter_svg: ^0.12.4
  # https://github.com/dart-lang/json_serializable/tree/master/example
  # packages pub run build_runner build
  json_annotation: ^2.0.0
  # https://github.com/AppleEducate/plugins
  # https://pub.dartlang.org/packages/flutter_whatsnew
  flutter_whatsnew: ^0.3.0
  # https://pub.dartlang.org/packages/native_widgets
  native_widgets: ^1.2.0
  # https://github.com/AppleEducate/plugins/tree/master/packages/persist_theme
  persist_theme: ^1.0.1+1
  # https://github.com/brianegan/scoped_model
  scoped_model: ^1.0.1
  # # https://github.com/flutter/plugins
  # local_auth: ^0.4.0+1
  # # https://github.com/AppleEducate/plugins/tree/master/packages/get_version
  # get_version: ^0.1.0
  # # https://github.com/AppleEducate/plugins/tree/master/packages/app_review
  # app_review: ^0.1.1+1
  # # https://github.com/AppleEducate/plugins/tree/master/packages/floating_search_bar
  # floating_search_bar: ^0.2.0


dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - CHANGELOG.md
    - assets/images/
    - assets/images/3.0x/
    - assets/images/icon/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
